networks:
  default:
    driver: bridge
  socket_proxy:
    name: socket_proxy
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.91.0/24
  t3_proxy:
    name: t3_proxy
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.90.0/24

secrets:
  basic_auth_credentials:
    file: $SECRETSDIR/basic_auth_credentials
  cf_dns_api_token:
    file: $SECRETSDIR/cf_dns_api_token
  traefik_forward_auth:
    file: $SECRETSDIR/traefik_forward_auth
  mysql_root_password:
    file: $SECRETSDIR/mysql_root_password
  authelia_jwt_secret:
    file: $SECRETSDIR/authelia_jwt_secret
  authelia_session_secret:
    file: $SECRETSDIR/authelia_session_secret
  # authelia_storage_mysql_password:
  #   file: $SECRETSDIR/secrets/authelia_storage_mysql_password
  # authelia_notifier_smtp_password:
  #   file: $SECRETSDIR/secrets/authelia_notifier_smtp_password
  # authelia_duo_api_secret_key:
  #   file: $SECRETSDIR/secrets/authelia_duo_api_secret_key
  authelia_storage_encryption_key:
    file: $SECRETSDIR/authelia_storage_encryption_key
  guac_db_name:
    file: $SECRETSDIR/guac_db_name
  guac_mysql_user:
    file: $SECRETSDIR/guac_mysql_user
  guac_mysql_password:
    file: $SECRETSDIR/guac_mysql_password

include:
  # These are enabled but wont be turned off with restarts:
  # - $USERDIR/docker/homelab/compose/docker-compose-gatus.yaml
  # - $USERDIR/docker/homelab/compose/docker-compose-portainer.yaml
  # - $USERDIR/docker/homelab/compose/docker-compose-ddclient.yaml
  # - $USERDIR/docker/homelab/compose/docker-compose-adguard.yaml

  - $USERDIR/docker/homelab/compose/docker-compose-docker-timemachine.yaml

  # CORE
  - $USERDIR/docker/homelab/compose/docker-compose-traefik.yaml
  - $USERDIR/docker/homelab/compose/docker-compose-socket-proxy.yaml
  - $USERDIR/docker/homelab/compose/docker-compose-oauth.yaml
  - $USERDIR/docker/homelab/compose/docker-compose-wizarr.yaml
  # - $USERDIR/docker/homelab/compose/docker-compose-authelia.yaml
  - $USERDIR/docker/homelab/compose/docker-compose-dockge.yaml
  # SECURITY
  # - $USERDIR/docker/homelab/compose/docker-compose-crowdsec.yaml
  # - $USERDIR/docker/homelab/compose/docker-compose-traefik-bouncer.yaml
  # FRONTEND
  - $USERDIR/docker/homelab/compose/docker-compose-jellyfin.yaml
  - $USERDIR/docker/homelab/compose/docker-compose-jellyseer.yaml
  # - $USERDIR/docker/homelab/compose/docker-compose-autoindex.yaml
  # - $USERDIR/docker/homelab/compose/docker-compose-homepage.yaml
  # - $USERDIR/docker/homelab/compose/docker-compose-phpmyadmin.yaml
  # - $USERDIR/docker/homelab/compose/docker-compose-sitespeed.yaml
  - $USERDIR/docker/homelab/compose/docker-compose-whoami.yaml
  # DOWNLOADERS
  # - $USERDIR/docker/homelab/compose/docker-compose-qbittorrent.yaml
  - $USERDIR/docker/homelab/compose/docker-compose-sabnzbd.yaml
  # PVRS
  - $USERDIR/docker/homelab/compose/docker-compose-sonarr.yaml
  - $USERDIR/docker/homelab/compose/docker-compose-readarr.yaml
  - $USERDIR/docker/homelab/compose/docker-compose-radarr.yaml
  - $USERDIR/docker/homelab/compose/docker-compose-audiobookshelf.yaml
  # - $USERDIR/docker/homelab/compose/docker-compose-lidarr.yaml
  # - $USERDIR/docker/homelab/compose/docker-compose-bazarr.yaml
  # COMPLEMENTARY APPS
  - $USERDIR/docker/homelab/compose/docker-compose-prowlarr.yaml
  # - $USERDIR/docker/homelab/compose/docker-compose-notifiarr.yaml
  # MONITORING
  # - $USERDIR/docker/homelab/compose/docker-compose-grafana.yaml
  - $USERDIR/docker/homelab/compose/docker-compose-dozzle.yaml
  # - $USERDIR/docker/homelab/compose/docker-compose-scrutiny.yaml
  # ADMIN
  # - $USERDIR/docker/homelab/compose/docker-compose-guacamole.yaml
  - $USERDIR/docker/homelab/compose/docker-compose-it-tools.yaml
  - $USERDIR/docker/homelab/compose/docker-compose-cyberchef.yaml
  # UTILITIES
  # - $USERDIR/docker/homelab/compose/docker-compose-firefly.yaml
  # FILE MANAGEMENT
  # - $USERDIR/docker/homelab/compose/docker-compose-vscode.yaml
  # - $USERDIR/docker/homelab/compose/docker-compose-makemkv.yaml
  # - $USERDIR/docker/homelab/compose/docker-compose-mkvtoolnix.yaml
  # NETWORK
  # - $USERDIR/docker/homelab/compose/docker-compose-gluetun.yaml
  # MAINTENANCE
  # - $USERDIR/docker/homelab/compose/docker-compose-docker-gc.yaml
  # - $USERDIR/docker/homelab/compose/docker-compose-deunhealth.yaml
  # uninterested
  # - $USERDIR/docker/homelab/compose/docker-compose-radarr-exporter.yaml
  # - $USERDIR/docker/homelab/compose/docker-compose-sonarr-exporter.yaml
  # - $USERDIR/docker/homelab/compose/docker-compose-lidarr-exporter.yaml
  # - $USERDIR/docker/homelab/compose/docker-compose-prowlarr-exporter.yaml
  # - $USERDIR/docker/homelab/compose/docker-compose-sabnzbd-exporter.yaml
  # - $USERDIR/docker/homelab/compose/docker-compose-kasm.yaml
  # - $USERDIR/docker/homelab/compose/docker-compose-picard.yaml
  # - $USERDIR/docker/homelab/compose/docker-compose-jdownloader.yaml
  # - $USERDIR/docker/homelab/compose/docker-compose-firefox.yaml
  # - $USERDIR/docker/homelab/compose/docker-compose-node-exporter.yaml
