networks:
  default:
    driver: bridge
  socket_proxy:
    name: socket_proxy
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.91.0/24
  t3_proxy:
    name: t3_proxy
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.90.0/24

secrets:
  basic_auth_credentials:
    file: $SECRETSDIR/basic_auth_credentials
  cf_dns_api_token:
    file: $SECRETSDIR/cf_dns_api_token
  traefik_forward_auth:
    file: $SECRETSDIR/traefik_forward_auth
  mysql_root_password:
    file: $SECRETSDIR/mysql_root_password
  authelia_jwt_secret:
    file: $SECRETSDIR/authelia_jwt_secret
  authelia_session_secret:
    file: $SECRETSDIR/authelia_session_secret
  # authelia_storage_mysql_password:
  #   file: $SECRETSDIR/secrets/authelia_storage_mysql_password
  # authelia_notifier_smtp_password:
  #   file: $SECRETSDIR/secrets/authelia_notifier_smtp_password
  # authelia_duo_api_secret_key:
  #   file: $SECRETSDIR/secrets/authelia_duo_api_secret_key
  authelia_storage_encryption_key:
    file: $SECRETSDIR/authelia_storage_encryption_key
  guac_db_name:
    file: $SECRETSDIR/guac_db_name
  guac_mysql_user:
    file: $SECRETSDIR/guac_mysql_user
  guac_mysql_password:
    file: $SECRETSDIR/guac_mysql_password

include:
  # These are enabled but wont be turned off with restarts:
  - $USERDIR/docker/homelab/active/gatus.yaml
  - $USERDIR/docker/homelab/active/portainer.yaml
  - $USERDIR/docker/homelab/active/traefik.yaml
  - $USERDIR/docker/homelab/active/ddclient.yaml
  - $USERDIR/docker/homelab/active/adguard.yaml
#  - $USERDIR/docker/homelab/active/tailscale.yaml

  - $USERDIR/docker/homelab/active/anythingllm.yaml
  - $USERDIR/docker/homelab/active/ollama.yaml
  - $USERDIR/docker/homelab/active/open-webui.yaml

  - $USERDIR/docker/homelab/active/changedetectionio.yaml

  - $USERDIR/docker/homelab/active/nextcloud.yaml

  - $USERDIR/docker/homelab/active/bazarr.yaml

#  - $USERDIR/docker/homelab/active/gekko.yaml
  - $USERDIR/docker/homelab/active/home-assistant.yaml
#  - $USERDIR/docker/homelab/active/actual-server.yaml
  - $USERDIR/docker/homelab/active/timemachine.yaml
  - $USERDIR/docker/homelab/active/tubesync.yaml
  - $USERDIR/docker/homelab/active/socket-proxy.yaml
  - $USERDIR/docker/homelab/active/oauth.yaml
  - $USERDIR/docker/homelab/active/wizarr.yaml

#  - $USERDIR/docker/homelab/active/gluetun.yaml
#  - $USERDIR/docker/homelab/active/deluge.yaml
  - $USERDIR/docker/homelab/active/flaresolverr.yaml
  
  - $USERDIR/docker/homelab/active/jellyfin.yaml
  - $USERDIR/docker/homelab/active/jellyseer.yaml
  - $USERDIR/docker/homelab/active/whoami.yaml
  - $USERDIR/docker/homelab/active/sabnzbd.yaml

  - $USERDIR/docker/homelab/active/lazylibrarian.yaml
  - $USERDIR/docker/homelab/active/kavita.yaml
  - $USERDIR/docker/homelab/active/calibre.yaml
  
  - $USERDIR/docker/homelab/active/sonarr.yaml
#  - $USERDIR/docker/homelab/active/readarr.yaml
  - $USERDIR/docker/homelab/active/radarr.yaml
  - $USERDIR/docker/homelab/active/recommendarr.yaml

  - $USERDIR/docker/homelab/active/prowlarr.yaml
  - $USERDIR/docker/homelab/active/it-tools.yaml
  - $USERDIR/docker/homelab/active/cyberchef.yaml

  - $USERDIR/docker/homelab/active/mqtt.yaml
  - $USERDIR/docker/homelab/active/watchtower.yaml
