networks:
  default:
    driver: bridge
  socket_proxy:
    name: socket_proxy
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.91.0/24
  t3_proxy:
    name: t3_proxy
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.90.0/24

secrets:
  basic_auth_credentials:
    file: $SECRETSDIR/basic_auth_credentials
  cf_dns_api_token:
    file: $SECRETSDIR/cf_dns_api_token
  traefik_forward_auth:
    file: $SECRETSDIR/traefik_forward_auth
  mysql_root_password:
    file: $SECRETSDIR/mysql_root_password
  authelia_jwt_secret:
    file: $SECRETSDIR/authelia_jwt_secret
  authelia_session_secret:
    file: $SECRETSDIR/authelia_session_secret
  # authelia_storage_mysql_password:
  #   file: $SECRETSDIR/secrets/authelia_storage_mysql_password
  # authelia_notifier_smtp_password:
  #   file: $SECRETSDIR/secrets/authelia_notifier_smtp_password
  # authelia_duo_api_secret_key:
  #   file: $SECRETSDIR/secrets/authelia_duo_api_secret_key
  authelia_storage_encryption_key:
    file: $SECRETSDIR/authelia_storage_encryption_key
  guac_db_name:
    file: $SECRETSDIR/guac_db_name
  guac_mysql_user:
    file: $SECRETSDIR/guac_mysql_user
  guac_mysql_password:
    file: $SECRETSDIR/guac_mysql_password

include:
  # These are enabled but wont be turned off with restarts:
  # - $USERDIR/docker/homelab/active/docker-compose-gatus.yaml
  # - $USERDIR/docker/homelab/active/docker-compose-portainer.yaml
  # - $USERDIR/docker/homelab/active/docker-compose-ddclient.yaml
  # - $USERDIR/docker/homelab/active/docker-compose-adguard.yaml

  # - $USERDIR/docker/homelab/active/docker-compose-obsidian.yaml
  
  - $USERDIR/docker/homelab/active/docker-compose-timemachine.yaml
  - $USERDIR/docker/homelab/active/docker-compose-tubesync.yaml
  - $USERDIR/docker/homelab/active/docker-compose-traefik.yaml
  - $USERDIR/docker/homelab/active/docker-compose-socket-proxy.yaml
  - $USERDIR/docker/homelab/active/docker-compose-oauth.yaml
  - $USERDIR/docker/homelab/active/docker-compose-wizarr.yaml
  
  - $USERDIR/docker/homelab/active/docker-compose-jellyfin.yaml
  - $USERDIR/docker/homelab/active/docker-compose-jellyseer.yaml
  - $USERDIR/docker/homelab/active/docker-compose-whoami.yaml
  - $USERDIR/docker/homelab/active/docker-compose-sabnzbd.yaml
  
  - $USERDIR/docker/homelab/active/docker-compose-sonarr.yaml
  - $USERDIR/docker/homelab/active/docker-compose-readarr.yaml
  - $USERDIR/docker/homelab/active/docker-compose-radarr.yaml

  - $USERDIR/docker/homelab/active/docker-compose-prowlarr.yaml
  - $USERDIR/docker/homelab/active/docker-compose-it-tools.yaml
  - $USERDIR/docker/homelab/active/docker-compose-cyberchef.yaml

