#!/usr/bin/env bash
set -euo pipefail
umask 077

HERE=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
STATE=/srv/devctl
CONFIG=$HERE/devctl.env
PROJECTS=$HERE/projects
RAW=https://raw.githubusercontent.com/LucUrlings/devctl/main/deploy

die() { echo "setup.sh: $*" >&2; exit 2; }
root() {
  if [[ $(id -u) == 0 ]]; then
    "$@"
  else
    sudo "$@"
  fi
}
compose_hub() { docker compose --env-file "$HERE/hub.env" -f "$HERE/hub.compose.yml" "$@"; }

ensure_bundle() {
  local refresh=${1:-false} file staged cache_bust stage_dir
  local -a downloaded=()
  cache_bust=$(date +%s)
  stage_dir=$(mktemp -d "$HERE/.bundle.XXXXXX")
  for file in hub.compose.yml hub.env.example workspace.compose.yml workspace.env.example; do
    if [[ $refresh == true || ! -f $HERE/$file ]]; then
      staged=$stage_dir/$file
      if ! curl -fsSL "$RAW/$file?devctl_cache=$cache_bust" -o "$staged" || [[ ! -s $staged ]]; then
        rm -f -- "$staged"
        for staged in "${downloaded[@]}"; do rm -f -- "$stage_dir/$staged"; done
        rmdir -- "$stage_dir"
        die "could not download $file"
      fi
      downloaded+=("$file")
    fi
  done
  for file in "${downloaded[@]}"; do mv -- "$stage_dir/$file" "$HERE/$file"; done
  rmdir -- "$stage_dir"
}

refresh_self() {
  [[ ${DEVCTL_SETUP_REFRESHED:-false} == true ]] && return
  local temporary=$HERE/.setup.sh.$$ cache_bust
  cache_bust=$(date +%s)
  if ! curl -fsSL "$RAW/setup.sh?devctl_cache=$cache_bust" -o "$temporary" || \
    [[ ! -s $temporary ]] || ! bash -n "$temporary"; then
    rm -f -- "$temporary"
    die "could not update setup.sh"
  fi
  chmod 0755 "$temporary"
  if cmp -s -- "$temporary" "$HERE/setup.sh"; then
    rm -f -- "$temporary"
    return
  fi
  mv -- "$temporary" "$HERE/setup.sh"
  echo "Updated setup.sh; continuing."
  DEVCTL_SETUP_REFRESHED=true exec "$HERE/setup.sh" "$@"
}

prepare_projects_dir() {
  [[ ! -e $PROJECTS || -d $PROJECTS ]] || die "$PROJECTS is not a directory"
  [[ ! -d $PROJECTS || -w $PROJECTS ]] || root chown "$(id -u):$(id -g)" "$PROJECTS"
  install -d -m 0700 "$PROJECTS"
}

usage() {
  cat <<'EOF'
Usage:
  ./setup.sh install --agent codex|claude|none [global options]
  ./setup.sh create <repo> [--name NAME] [--branch BRANCH] [--depth N]
                          [--preview-port PORT] [--ssh-port PORT]
  ./setup.sh agent PROJECT codex|claude|shell
  ./setup.sh update [PROJECT]
  ./setup.sh teardown PROJECT|--all
  ./setup.sh list
  ./setup.sh telegram --token-file PATH --allowed-users IDS --group-id ID
  ./setup.sh login github|codex|claude

Global options:
  --base-domain DOMAIN --traefik-network NETWORK
  --auth-middleware MIDDLEWARE [--entrypoint NAME] [--cert-resolver NAME]
  --authorized-key PATH
EOF
}

valid_name() { [[ $1 =~ ^[a-z0-9][a-z0-9-]{0,40}$ ]]; }
valid_repo() { [[ $1 =~ ^https://[A-Za-z0-9.-]+/[A-Za-z0-9._~/%+-]+$ ]]; }
valid_domain() {
  [[ $1 =~ ^[A-Za-z0-9]([A-Za-z0-9-]*[A-Za-z0-9])?(\.[A-Za-z0-9]([A-Za-z0-9-]*[A-Za-z0-9])?)+$ ]]
}
valid_num() { [[ $1 =~ ^[0-9]+$ && ${#1} -le 10 ]] && (( 10#$1 >= $2 && 10#$1 <= $3 )); }
valid_branch() { [[ -z $1 || ( $1 =~ ^[A-Za-z0-9][A-Za-z0-9._/-]{0,254}$ && $1 != *..* && $1 != *//* ) ]]; }

load_config() {
  [[ -f $CONFIG ]] || die "run './setup.sh install' first"
  # The file is generated by this script and contains validated values only.
  # shellcheck disable=SC1090
  source "$CONFIG"
}

wait_healthy() {
  local project=$1 file=$2 compose_file=$3 service=$4 id health
  for _ in {1..150}; do
    id=$(docker compose --project-name "$project" --env-file "$file" \
      -f "$compose_file" ps --all --quiet "$service" 2>/dev/null || true)
    if [[ -n $id ]]; then
      health=$(docker inspect --format '{{if .State.Health}}{{.State.Health.Status}}{{else}}{{.State.Status}}{{end}}' "$id")
      [[ $health == healthy ]] && return
      [[ $health == unhealthy || $health == exited ]] && die "$service failed; inspect Compose logs"
    fi
    sleep 2
  done
  die "$service did not become healthy"
}

install_key() {
  local source=$1 line
  [[ -f $source ]] || die "SSH key file not found: $source"
  root install -d -m 0755 "$STATE/ssh"
  root touch "$STATE/ssh/authorized_keys"
  while IFS= read -r line || [[ -n $line ]]; do
    [[ -z ${line//[[:space:]]/} || $line =~ ^[[:space:]]*# ]] && continue
    [[ $line =~ (ssh-ed25519|ssh-rsa|ecdsa-sha2-nistp(256|384|521))[[:space:]][A-Za-z0-9+/=]+ ]] || die "invalid public key in $source"
    root grep -Fqx -- "$line" "$STATE/ssh/authorized_keys" || printf '%s\n' "$line" | root tee -a "$STATE/ssh/authorized_keys" >/dev/null
  done < "$source"
  root chmod 0600 "$STATE/ssh/authorized_keys"
}

install_cmd() {
  local agent='' domain='' network='' middleware='' entrypoint=websecure resolver='' key='' no_start=false
  while (($#)); do
    case $1 in
      --agent) agent=${2:-}; shift 2;;
      --base-domain) domain=${2:-}; shift 2;;
      --traefik-network) network=${2:-}; shift 2;;
      --auth-middleware) middleware=${2:-}; shift 2;;
      --entrypoint) entrypoint=${2:-}; shift 2;;
      --cert-resolver) resolver=${2:-}; shift 2;;
      --authorized-key) key=${2:-}; shift 2;;
      --no-start) no_start=true; shift;;
      *) die "unknown install option: $1";;
    esac
  done
  [[ $agent == codex || $agent == claude || $agent == none ]] || die "--agent must be codex, claude, or none"
  [[ -n $domain ]] || read -r -p 'Base domain: ' domain
  [[ -n $network ]] || read -r -p 'Traefik network: ' network
  [[ -n $middleware ]] || read -r -p 'Traefik OAuth middleware: ' middleware
  valid_domain "$domain" || die "invalid base domain"
  [[ $network =~ ^[A-Za-z0-9_.-]+$ ]] || die "invalid Traefik network"
  [[ $middleware =~ ^[A-Za-z0-9_.@:-]+$ ]] || die "invalid OAuth middleware"
  ensure_bundle true
  prepare_projects_dir
  [[ $entrypoint =~ ^[A-Za-z0-9_.-]+$ ]] || die "invalid Traefik entrypoint"
  [[ -z $resolver || $resolver =~ ^[A-Za-z0-9_.-]+$ ]] || die "invalid certificate resolver"
  root install -d -m 0755 "$STATE/herdr" "$STATE/herdr/run" "$STATE/ccgram" "$STATE/projects"
  root install -d -m 0700 "$STATE/secrets" "$STATE/shared/codex" "$STATE/shared/claude" "$STATE/shared/gh"
  root install -d -m 0755 "$STATE/ssh"
  root touch "$STATE/ssh/authorized_keys"
  root chmod 0600 "$STATE/ssh/authorized_keys"
  [[ -f $HERE/hub.env ]] || cp -- "$HERE/hub.env.example" "$HERE/hub.env"
  chmod 0600 "$HERE/hub.env"
  if [[ -n $key ]]; then install_key "$key"; elif [[ -f $HOME/.ssh/authorized_keys ]]; then install_key "$HOME/.ssh/authorized_keys"; fi
  printf '%s\n' "BASE_DOMAIN=$domain" "TRAEFIK_NETWORK=$network" "TRAEFIK_ENTRYPOINT=$entrypoint" \
    "TRAEFIK_AUTH_MIDDLEWARE=$middleware" "TRAEFIK_CERT_RESOLVER=$resolver" "DEFAULT_AGENT=$agent" > "$CONFIG"
  chmod 0600 "$CONFIG"
  if [[ $no_start == false ]]; then
    compose_hub up -d
    wait_healthy devctl-hub "$HERE/hub.env" "$HERE/hub.compose.yml" herdr
    [[ $agent == none ]] || login_cmd "$agent"
  fi
  echo "Installed. Run './setup.sh create <repo>' to create a workspace."
}

port_free() {
  local port=$1 file configured port_hex
  local -a tcp_tables=(/proc/net/tcp)
  for file in "$PROJECTS"/*.env; do
    [[ -e $file ]] || continue
    configured=$(sed -n 's/^SSH_PORT=//p' "$file")
    [[ $configured == "$port" ]] && return 1
  done
  if [[ -n $(docker ps --filter "publish=$port" --format '{{.ID}}' 2>/dev/null) ]]; then
    return 1
  fi
  if command -v ss >/dev/null 2>&1; then
    ss -H -ltn | awk -v p="$port" '{ x=$4; sub(/^.*:/,"",x); if (x==p) found=1 } END { exit found }'
    return
  fi
  # Minimal Linux hosts may not include iproute2/ss. Check kernel TCP listener
  # tables directly instead of assuming that every unregistered port is free.
  [[ -r /proc/net/tcp ]] || return 1
  [[ ! -r /proc/net/tcp6 ]] || tcp_tables+=(/proc/net/tcp6)
  port_hex=$(printf '%04X' "$port")
  awk -v p="$port_hex" '$4 == "0A" && $2 ~ (":" p "$") { found=1 } END { exit found }' \
    "${tcp_tables[@]}" 2>/dev/null
}

next_port() {
  local port
  for port in $(seq 22000 22999); do port_free "$port" && { echo "$port"; return; }; done
  die "no SSH ports remain in 22000-22999"
}

project_name_from_file() {
  local file=$1 name
  name=$(sed -n 's/^PROJECT_NAME=//p' "$file")
  valid_name "$name" || die "invalid PROJECT_NAME in $file"
  [[ $file == "$PROJECTS/$name.env" ]] || die "project env filename does not match PROJECT_NAME: $file"
  printf '%s\n' "$name"
}

workspace_compose() {
  local name=$1 file=$2
  shift 2
  docker compose --project-name "devctl-$name" --env-file "$file" \
    -f "$HERE/workspace.compose.yml" "$@"
}

wait_pane_shell() {
  local pane=$1 info process
  for _ in {1..30}; do
    info=$(compose_hub exec -T herdr herdr pane process-info --pane "$pane" 2>/dev/null || true)
    process=$(printf '%s\n' "$info" | compose_hub exec -T herdr jq -r \
      '.result.process_info.foreground_processes[0].name // empty')
    [[ $process == sh || $process == bash || $process == zsh || $process == fish ]] && return
    sleep 1
  done
  die "Herdr pane $pane did not become ready"
}

wait_agent() {
  local pane=$1 agents found
  for _ in {1..30}; do
    agents=$(compose_hub exec -T herdr herdr agent list 2>/dev/null || true)
    # $pane belongs to jq, not the shell.
    # shellcheck disable=SC2016
    found=$(printf '%s\n' "$agents" | compose_hub exec -T herdr jq -r --arg pane "$pane" \
      'any(.result.agents[]?; .pane_id == $pane)')
    [[ $found == true ]] && return
    sleep 1
  done
  die "agent did not start in Herdr pane $pane; inspect it with 'herdr pane read $pane'"
}

run_agent_in_pane() {
  local pane=$1 project=$2 agent=$3 mode=${4:-new}
  if [[ $agent == shell ]]; then
    compose_hub exec -T herdr herdr pane run "$pane" \
      "exec dev-enter $project shell" >/dev/null
  else
    compose_hub exec -T herdr herdr pane run "$pane" \
      "exec dev-session $project $agent $mode" >/dev/null
  fi
}

reconcile_now() {
  compose_hub exec -T herdr hub-reconcile >/dev/null
}

herdr_create() {
  local project=$1 agent=${2:-${DEFAULT_AGENT:-none}} result workspace pane shell_tab tab tab_pane
  result=$(compose_hub exec -T herdr herdr workspace create --cwd /srv/devctl/herdr --label "$project" --no-focus)
  workspace=$(printf '%s\n' "$result" | compose_hub exec -T herdr jq -r '.result.workspace.workspace_id')
  pane=$(printf '%s\n' "$result" | compose_hub exec -T herdr jq -r '.result.root_pane.pane_id')
  shell_tab=$(printf '%s\n' "$result" | compose_hub exec -T herdr jq -r '.result.tab.tab_id')
  [[ $workspace != null && $pane != null && $shell_tab != null ]] || die "Herdr workspace creation failed"
  compose_hub exec -T herdr herdr tab rename "$shell_tab" shell >/dev/null
  wait_pane_shell "$pane"
  run_agent_in_pane "$pane" "$project" shell
  [[ $agent == none || $agent == shell ]] && return
  tab=$(compose_hub exec -T herdr herdr tab create --workspace "$workspace" --cwd /srv/devctl/herdr --label "$agent" --no-focus)
  tab_pane=$(printf '%s\n' "$tab" | compose_hub exec -T herdr jq -r '.result.root_pane.pane_id')
  [[ $tab_pane != null ]] || die "Herdr tab creation failed"
  wait_pane_shell "$tab_pane"
  run_agent_in_pane "$tab_pane" "$project" "$agent"
  wait_agent "$tab_pane"
}

set_project_agent() {
  set_env_value "$1" PROJECT_AGENT "$2"
}

set_env_value() {
  local file=$1 key=$2 value=$3 temporary=$1.tmp.$$
  awk -v key="$key" -v value="$value" '
    BEGIN { found = 0 }
    index($0, key "=") == 1 { if (!found) print key "=" value; found = 1; next }
    { print }
    END { if (!found) print key "=" value }
  ' "$file" > "$temporary"
  chmod 0600 "$temporary"
  mv -- "$temporary" "$file"
}

project_agent_from_file() {
  local file=$1 agent
  agent=$(sed -n 's/^PROJECT_AGENT=//p' "$file")
  [[ -n $agent ]] || agent=${DEFAULT_AGENT:-none}
  [[ $agent == codex || $agent == claude || $agent == shell || $agent == none ]] || \
    die "invalid PROJECT_AGENT in $file"
  printf '%s\n' "$agent"
}

# The single-quoted expressions contain jq variables supplied with --arg.
# shellcheck disable=SC2016
start_project_agent() {
  local project=$1 agent=$2 workspaces workspace_count workspace tabs tab_count tab panes pane_count pane process agents managed mode=resume
  workspaces=$(compose_hub exec -T herdr herdr workspace list)
  workspace_count=$(printf '%s\n' "$workspaces" | compose_hub exec -T herdr jq -r --arg label "$project" \
    '[.result.workspaces[]? | select(.label == $label)] | length')
  if [[ $workspace_count == 0 ]]; then
    herdr_create "$project" "$agent"
    return
  fi
  [[ $workspace_count == 1 ]] || die "multiple Herdr workspaces match project $project"
  [[ $agent == none ]] && return
  workspace=$(printf '%s\n' "$workspaces" | compose_hub exec -T herdr jq -r --arg label "$project" \
    '.result.workspaces[] | select(.label == $label) | .workspace_id')

  tabs=$(compose_hub exec -T herdr herdr tab list --workspace "$workspace")
  tab_count=$(printf '%s\n' "$tabs" | compose_hub exec -T herdr jq -r --arg label "$agent" \
    '[.result.tabs[]? | select(.label == $label)] | length')
  [[ $tab_count -le 1 ]] || die "multiple $agent tabs exist for project $project"
  if [[ $tab_count == 0 ]]; then
    mode=new
    tab=$(compose_hub exec -T herdr herdr tab create --workspace "$workspace" \
      --cwd /srv/devctl/herdr --label "$agent" --no-focus)
    pane=$(printf '%s\n' "$tab" | compose_hub exec -T herdr jq -r '.result.root_pane.pane_id')
    [[ $pane != null ]] || die "Herdr tab creation failed"
  else
    tab=$(printf '%s\n' "$tabs" | compose_hub exec -T herdr jq -r --arg label "$agent" \
      '.result.tabs[] | select(.label == $label) | .tab_id')
    panes=$(compose_hub exec -T herdr herdr pane list --workspace "$workspace")
    pane_count=$(printf '%s\n' "$panes" | compose_hub exec -T herdr jq -r --arg tab "$tab" \
      '[.result.panes[]? | select(.tab_id == $tab)] | length')
    [[ $pane_count == 1 ]] || die "$project $agent tab must contain exactly one pane"
    pane=$(printf '%s\n' "$panes" | compose_hub exec -T herdr jq -r --arg tab "$tab" \
      '.result.panes[] | select(.tab_id == $tab) | .pane_id')
  fi

  agents=$(compose_hub exec -T herdr herdr agent list)
  if [[ $(printf '%s\n' "$agents" | compose_hub exec -T herdr jq -r --arg pane "$pane" \
    'any(.result.agents[]?; .pane_id == $pane)') == true ]]; then
    echo "$project $agent is already running."
    return
  fi
  process=$(compose_hub exec -T herdr herdr pane process-info --pane "$pane" | \
    compose_hub exec -T herdr jq -r '.result.process_info.foreground_processes[0].name // empty')
  if [[ $agent == shell && $process == docker ]]; then
    echo "$project shell is already running."
    return
  fi
  managed=$(compose_hub exec -T herdr herdr pane process-info --pane "$pane" | \
    compose_hub exec -T herdr jq -r --arg project "$project" --arg agent "$agent" \
      'any(.result.process_info.foreground_processes[]?; ((.argv // []) | join(" ") | contains("/usr/local/bin/dev-session " + $project + " " + $agent)))')
  if [[ $managed == true ]]; then
    wait_agent "$pane"
    return
  fi
  wait_pane_shell "$pane"
  run_agent_in_pane "$pane" "$project" "$agent" "$mode"
  [[ $agent == shell ]] || wait_agent "$pane"
}

agent_cmd() {
  (($# == 2)) || die "agent requires a project and codex, claude, or shell"
  local project=$1 agent=$2 file configured_project container
  valid_name "$project" || die "invalid project name"
  [[ $agent == codex || $agent == claude || $agent == shell ]] || \
    die "agent must be codex, claude, or shell"
  ensure_bundle
  load_config
  prepare_projects_dir
  file=$PROJECTS/$project.env
  [[ -f $file ]] || die "project not found: $project"
  configured_project=$(project_name_from_file "$file")
  [[ $configured_project == "$project" ]] || die "project configuration mismatch"
  # Persist the fallback before creating a replacement container. Otherwise a
  # project restarted after teardown can briefly reconcile its previous agent.
  set_project_agent "$file" "$agent"
  container=$(workspace_compose "$project" "$file" ps --all --quiet workspace)
  if [[ -n $container ]]; then
    workspace_compose "$project" "$file" start workspace
  else
    workspace_compose "$project" "$file" up -d workspace
  fi
  wait_healthy "devctl-$project" "$file" "$HERE/workspace.compose.yml" workspace
  reconcile_now
  start_project_agent "$project" "$agent"
  echo "Agent ready: $project $agent"
}

create_cmd() {
  ensure_bundle
  load_config
  local repo=$1 name='' branch='' depth='' preview=3000 port='' file project_dir
  shift
  while (($#)); do
    case $1 in
      --name) name=${2:-}; shift 2;;
      --branch) branch=${2:-}; shift 2;;
      --depth) depth=${2:-}; shift 2;;
      --preview-port) preview=${2:-}; shift 2;;
      --ssh-port) port=${2:-}; shift 2;;
      *) die "unknown create option: $1";;
    esac
  done
  valid_repo "$repo" || die "repository must be a credential-free HTTPS URL"
  valid_branch "$branch" || die "invalid branch"
  [[ -z $depth ]] || valid_num "$depth" 1 2147483647 || die "invalid clone depth"
  [[ -n $name ]] || name=${repo##*/}; name=${name%.git}; name=$(printf '%s' "$name" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9-]/-/g; s/--*/-/g; s/^-*//; s/-*$//; s/\(.........................................\).*/\1/')
  valid_name "$name" || die "could not derive a valid project name; use --name"
  valid_num "$preview" 1 65535 || die "preview port is invalid"
  prepare_projects_dir
  command -v flock >/dev/null 2>&1 || die "flock is required"
  exec 9>"$PROJECTS/.lock"
  flock -x 9
  file=$PROJECTS/$name.env
  [[ ! -e $file ]] || die "project already exists: $name; use './setup.sh update $name' or './setup.sh agent $name <agent>'"
  if [[ -z $port ]]; then
    port=$(next_port)
  else
    valid_num "$port" 22000 22999 || die "SSH port must be 22000-22999"
    port_free "$port" || die "SSH port $port is already allocated or in use"
  fi
  project_dir=$STATE/projects/$name
  root install -d -m 0755 "$project_dir"
  root install -d -m 0700 "$project_dir/repo" "$project_dir/ssh-host-keys" "$project_dir/vscode-server"
  printf '%s\n' "PROJECT_NAME=$name" "PROJECT_DIR=$project_dir" "REPO_URL=$repo" "REPO_BRANCH=$branch" "REPO_DEPTH=$depth" \
    "SSH_PORT=$port" "PREVIEW_PORT=$preview" "BASE_DOMAIN=$BASE_DOMAIN" "TRAEFIK_NETWORK=$TRAEFIK_NETWORK" \
    "TRAEFIK_ENTRYPOINT=$TRAEFIK_ENTRYPOINT" "TRAEFIK_AUTH_MIDDLEWARE=$TRAEFIK_AUTH_MIDDLEWARE" \
    "TRAEFIK_CERT_RESOLVER=$TRAEFIK_CERT_RESOLVER" "PROJECT_AGENT=$DEFAULT_AGENT" \
    "WORKSPACE_IMAGE=ghcr.io/lucurlings/devctl-workspace:latest" \
    'WORKSPACE_CPUS=4' 'WORKSPACE_MEMORY=8G' > "$file.tmp.$$"
  chmod 0600 "$file.tmp.$$"
  mv -- "$file.tmp.$$" "$file"
  flock -u 9
  exec 9>&-
  docker compose --project-name "devctl-$name" --env-file "$file" -f "$HERE/workspace.compose.yml" up -d
  wait_healthy "devctl-$name" "$file" "$HERE/workspace.compose.yml" workspace
  reconcile_now
  start_project_agent "$name" "$DEFAULT_AGENT"
  cat <<EOF
Created $name
Code: https://$name.code.$BASE_DOMAIN
Preview: https://$name.dev.$BASE_DOMAIN

Add this block to your laptop's ~/.ssh/config:
Host dev-$name
    HostName 127.0.0.1
    Port $port
    User developer
    ProxyJump <server-alias>
    IdentityFile ~/.ssh/id_ed25519
EOF
}

# Print the exact Herdr workspace ID for a project, or nothing when the hub or
# workspace is absent. Refuse ambiguity instead of closing an unintended workspace.
# The single-quoted expressions contain jq variables supplied with --arg.
# shellcheck disable=SC2016
project_workspace_id() {
  local project=$1 workspaces count
  [[ -f $HERE/hub.env && -f $HERE/hub.compose.yml ]] || return 0
  [[ -n $(compose_hub ps --status running --quiet herdr 2>/dev/null) ]] || return 0
  workspaces=$(compose_hub exec -T herdr herdr workspace list)
  count=$(printf '%s\n' "$workspaces" | compose_hub exec -T herdr jq -r --arg label "$project" \
    '[.result.workspaces[]? | select(.label == $label)] | length')
  [[ $count -le 1 ]] || die "multiple Herdr workspaces match project $project"
  [[ $count == 1 ]] || return 0
  printf '%s\n' "$workspaces" | compose_hub exec -T herdr jq -r --arg label "$project" \
    '.result.workspaces[] | select(.label == $label) | .workspace_id'
}

update_cmd() {
  (($# <= 1)) || die "update accepts at most one project"
  ensure_bundle true
  [[ -f $HERE/hub.env ]] || die "run './setup.sh install' first"
  load_config
  prepare_projects_dir

  local -a files=()
  local file name agent hub_container restart_telegram=false update_hub=false
  if [[ -n $(compose_hub --profile telegram ps --status running --quiet telegram 2>/dev/null) ]]; then
    compose_hub --profile telegram stop telegram
    restart_telegram=true
    trap 'if [[ ${restart_telegram:-false} == true ]]; then compose_hub --profile telegram up -d telegram >/dev/null 2>&1 || true; fi' EXIT
  fi

  if (($# == 1)); then
    valid_name "$1" || die "invalid project name"
    [[ -f $PROJECTS/$1.env ]] || die "project not found: $1"
    files=("$PROJECTS/$1.env")
  else
    update_hub=true
    shopt -s nullglob
    files=("$PROJECTS"/*.env)
    shopt -u nullglob
    compose_hub up -d --pull always --force-recreate --remove-orphans herdr
  fi
  if [[ $update_hub == false ]]; then
    hub_container=$(compose_hub ps --all --quiet herdr 2>/dev/null || true)
    if [[ -n $hub_container ]]; then
      compose_hub start herdr
    else
      compose_hub up -d --pull missing herdr
    fi
  fi
  wait_healthy devctl-hub "$HERE/hub.env" "$HERE/hub.compose.yml" herdr

  for file in "${files[@]}"; do
    name=$(project_name_from_file "$file")
    workspace_compose "$name" "$file" up -d --pull always --force-recreate --remove-orphans
    wait_healthy "devctl-$name" "$file" "$HERE/workspace.compose.yml" workspace
    reconcile_now
    agent=$(project_agent_from_file "$file")
    [[ $agent == none ]] || start_project_agent "$name" "$agent"
  done
  if [[ $restart_telegram == true ]]; then
    if [[ $update_hub == true ]]; then
      compose_hub --profile telegram up -d --pull always --force-recreate telegram
    else
      compose_hub --profile telegram start telegram
    fi
    wait_healthy devctl-hub "$HERE/hub.env" "$HERE/hub.compose.yml" telegram
    restart_telegram=false
  fi
  trap - EXIT
  if (($# == 1)); then
    echo "Updated $1. Persistent data was preserved."
  else
    echo "Updated hub and ${#files[@]} workspace(s). Persistent data was preserved."
  fi
}

teardown_cmd() {
  (($# == 1)) || die "teardown requires a project name or --all"
  [[ -f $HERE/workspace.compose.yml ]] || die "workspace.compose.yml is missing"
  prepare_projects_dir

  local file name workspace close_output
  if [[ $1 == --all ]]; then
    local -a files=()
    shopt -s nullglob
    files=("$PROJECTS"/*.env)
    shopt -u nullglob
    for file in "${files[@]}"; do
      name=$(project_name_from_file "$file")
      workspace_compose "$name" "$file" down --remove-orphans
    done
    [[ -f $HERE/hub.env && -f $HERE/hub.compose.yml ]] && \
      compose_hub --profile telegram down --remove-orphans
    echo "Tore down hub and ${#files[@]} workspace(s). Persistent data and config were preserved."
    return
  fi

  valid_name "$1" || die "invalid project name"
  file=$PROJECTS/$1.env
  [[ -f $file ]] || die "project not found: $1"
  name=$(project_name_from_file "$file")
  # Validate that the label resolves unambiguously before changing Docker state.
  project_workspace_id "$name" >/dev/null
  workspace_compose "$name" "$file" down --remove-orphans
  # Herdr may automatically remove the workspace when its final docker-exec pane
  # exits. Resolve it again so an already-completed close remains successful.
  workspace=$(project_workspace_id "$name")
  if [[ -n $workspace ]]; then
    if ! close_output=$(compose_hub exec -T herdr herdr workspace close "$workspace" 2>&1); then
      # The final docker-exec pane may exit between the lookup and close call,
      # causing Herdr to finish the same cleanup first. Only that exact race is
      # idempotent; surface every other failure.
      if [[ $close_output != *'"code":"workspace_not_found"'* ]]; then
        printf '%s\n' "$close_output" >&2
        die "could not close Herdr workspace $workspace"
      fi
    fi
  fi
  echo "Tore down $name. Its repository, credentials, SSH keys, and config were preserved."
}

login_cmd() {
  case ${1:-} in
    github) compose_hub exec --user developer -e HOME=/home/developer herdr gh auth login --hostname github.com --git-protocol https --web;;
    codex) compose_hub exec --user developer -e HOME=/home/developer herdr codex login --device-auth;;
    claude) compose_hub exec --user developer -e HOME=/home/developer herdr claude auth login;;
    *) die "login requires github, codex, or claude";;
  esac
}

list_cmd() { for file in "$PROJECTS"/*.env; do [[ -e $file ]] || continue; sed -n 's/^PROJECT_NAME=//p' "$file"; done; }

telegram_cmd() {
  ensure_bundle
  local token='' users='' group=''
  while (($#)); do case $1 in --token-file) token=${2:-}; shift 2;; --allowed-users) users=${2:-}; shift 2;; --group-id) group=${2:-}; shift 2;; *) die "unknown telegram option: $1";; esac; done
  [[ $users =~ ^[0-9]+(,[0-9]+)*$ && $group =~ ^-100[0-9]+$ && -f $token ]] || die "invalid Telegram settings"
  [[ $(stat -c '%a' "$token") == 600 ]] || die "token file must have mode 0600"
  [[ -f $HERE/hub.env ]] || die "run './setup.sh install' first"
  set_env_value "$HERE/hub.env" TELEGRAM_ALLOWED_USERS "$users"
  set_env_value "$HERE/hub.env" TELEGRAM_GROUP_ID "$group"
  root install -m 0600 "$token" "$STATE/secrets/telegram-bot-token"
  compose_hub --profile telegram up -d
  wait_healthy devctl-hub "$HERE/hub.env" "$HERE/hub.compose.yml" telegram
  echo "Telegram configured and running."
}

main() {
  case ${1:-} in
    install) shift; install_cmd "$@";;
    create) (($# >= 2)) || die "create requires a repository URL"; shift; create_cmd "$@";;
    agent) shift; agent_cmd "$@";;
    update) refresh_self "$@"; shift; update_cmd "$@";;
    teardown) shift; teardown_cmd "$@";;
    list) list_cmd;;
    telegram) shift; telegram_cmd "$@";;
    login) shift; login_cmd "$@";;
    -h|--help|help) usage;;
    *) usage; exit 2;;
  esac
}
main "$@"
