#!/usr/bin/env bash
set -euo pipefail
umask 077

HERE=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
STATE=/srv/devctl
CONFIG=$HERE/devctl.env
PROJECTS=$HERE/projects
RAW=https://raw.githubusercontent.com/LucUrlings/devctl/main/deploy

die() { echo "setup.sh: $*" >&2; exit 2; }
root() {
  if [[ $(id -u) == 0 ]]; then
    "$@"
  else
    sudo "$@"
  fi
}
compose_hub() { docker compose --env-file "$HERE/hub.env" -f "$HERE/hub.compose.yml" "$@"; }

ensure_bundle() {
  local file
  for file in hub.compose.yml hub.env.example workspace.compose.yml workspace.env.example workspace.docker-host.override.yml; do
    [[ -f $HERE/$file ]] || curl -fsSL "$RAW/$file" -o "$HERE/$file" || die "could not download $file"
  done
}

prepare_projects_dir() {
  [[ ! -e $PROJECTS || -d $PROJECTS ]] || die "$PROJECTS is not a directory"
  [[ ! -d $PROJECTS || -w $PROJECTS ]] || root chown "$(id -u):$(id -g)" "$PROJECTS"
  install -d -m 0700 "$PROJECTS"
}

usage() {
  cat <<'EOF'
Usage:
  ./setup.sh install --agent codex|claude|none [global options]
  ./setup.sh create <repo> [--name NAME] [--branch BRANCH] [--depth N]
  ./setup.sh list
  ./setup.sh telegram --token-file PATH --allowed-users IDS --group-id ID
  ./setup.sh login github|codex|claude

Global options:
  --base-domain DOMAIN --traefik-network NETWORK
  --auth-middleware MIDDLEWARE [--entrypoint NAME] [--cert-resolver NAME]
  --authorized-key PATH
EOF
}

valid_name() { [[ $1 =~ ^[a-z0-9][a-z0-9-]{0,40}$ ]]; }
valid_repo() { [[ $1 =~ ^https://[A-Za-z0-9.-]+/[A-Za-z0-9._~/%+-]+$ ]]; }
valid_domain() {
  [[ $1 =~ ^[A-Za-z0-9]([A-Za-z0-9-]*[A-Za-z0-9])?(\.[A-Za-z0-9]([A-Za-z0-9-]*[A-Za-z0-9])?)+$ ]]
}
valid_num() { [[ $1 =~ ^[0-9]+$ && ${#1} -le 10 ]] && (( 10#$1 >= $2 && 10#$1 <= $3 )); }
valid_branch() { [[ -z $1 || ( $1 =~ ^[A-Za-z0-9][A-Za-z0-9._/-]{0,254}$ && $1 != *..* && $1 != *//* ) ]]; }

load_config() {
  [[ -f $CONFIG ]] || die "run './setup.sh install' first"
  # The file is generated by this script and contains validated values only.
  # shellcheck disable=SC1090
  source "$CONFIG"
}

wait_healthy() {
  local project=$1 file=$2 compose_file=$3 service=$4 id health
  for _ in {1..150}; do
    id=$(docker compose --project-name "$project" --env-file "$file" \
      -f "$compose_file" ps --all --quiet "$service" 2>/dev/null || true)
    if [[ -n $id ]]; then
      health=$(docker inspect --format '{{if .State.Health}}{{.State.Health.Status}}{{else}}{{.State.Status}}{{end}}' "$id")
      [[ $health == healthy ]] && return
      [[ $health == unhealthy || $health == exited ]] && die "$service failed; inspect Compose logs"
    fi
    sleep 2
  done
  die "$service did not become healthy"
}

install_key() {
  local source=$1 line
  [[ -f $source ]] || die "SSH key file not found: $source"
  root install -d -m 0755 "$STATE/ssh"
  root touch "$STATE/ssh/authorized_keys"
  while IFS= read -r line || [[ -n $line ]]; do
    [[ -z ${line//[[:space:]]/} || $line =~ ^[[:space:]]*# ]] && continue
    [[ $line =~ (ssh-ed25519|ssh-rsa|ecdsa-sha2-nistp(256|384|521))[[:space:]][A-Za-z0-9+/=]+ ]] || die "invalid public key in $source"
    root grep -Fqx -- "$line" "$STATE/ssh/authorized_keys" || printf '%s\n' "$line" | root tee -a "$STATE/ssh/authorized_keys" >/dev/null
  done < "$source"
  root chmod 0600 "$STATE/ssh/authorized_keys"
}

install_cmd() {
  local agent='' domain='' network='' middleware='' entrypoint=websecure resolver='' key='' no_start=false
  while (($#)); do
    case $1 in
      --agent) agent=${2:-}; shift 2;;
      --base-domain) domain=${2:-}; shift 2;;
      --traefik-network) network=${2:-}; shift 2;;
      --auth-middleware) middleware=${2:-}; shift 2;;
      --entrypoint) entrypoint=${2:-}; shift 2;;
      --cert-resolver) resolver=${2:-}; shift 2;;
      --authorized-key) key=${2:-}; shift 2;;
      --no-start) no_start=true; shift;;
      *) die "unknown install option: $1";;
    esac
  done
  [[ $agent == codex || $agent == claude || $agent == none ]] || die "--agent must be codex, claude, or none"
  [[ -n $domain ]] || read -r -p 'Base domain: ' domain
  [[ -n $network ]] || read -r -p 'Traefik network: ' network
  [[ -n $middleware ]] || read -r -p 'Traefik OAuth middleware: ' middleware
  valid_domain "$domain" || die "invalid base domain"
  [[ $network =~ ^[A-Za-z0-9_.-]+$ ]] || die "invalid Traefik network"
  [[ $middleware =~ ^[A-Za-z0-9_.@:-]+$ ]] || die "invalid OAuth middleware"
  ensure_bundle
  prepare_projects_dir
  root install -d -m 0755 "$STATE/herdr" "$STATE/herdr/run" "$STATE/ccgram" "$STATE/projects"
  root install -d -m 0700 "$STATE/secrets" "$STATE/shared/codex" "$STATE/shared/claude" "$STATE/shared/gh"
  [[ -f $HERE/hub.env ]] || cp -- "$HERE/hub.env.example" "$HERE/hub.env"
  chmod 0600 "$HERE/hub.env"
  if [[ -n $key ]]; then install_key "$key"; elif [[ -f $HOME/.ssh/authorized_keys ]]; then install_key "$HOME/.ssh/authorized_keys"; fi
  printf '%s\n' "BASE_DOMAIN=$domain" "TRAEFIK_NETWORK=$network" "TRAEFIK_ENTRYPOINT=$entrypoint" \
    "TRAEFIK_AUTH_MIDDLEWARE=$middleware" "TRAEFIK_CERT_RESOLVER=$resolver" "DEFAULT_AGENT=$agent" > "$CONFIG"
  chmod 0600 "$CONFIG"
  if [[ $no_start == false ]]; then
    compose_hub up -d
    wait_healthy devctl-hub "$HERE/hub.env" "$HERE/hub.compose.yml" herdr
    [[ $agent == none ]] || login_cmd "$agent"
  fi
  echo "Installed. Run './setup.sh create <repo>' to create a workspace."
}

port_free() {
  local port=$1 file configured
  for file in "$PROJECTS"/*.env; do
    [[ -e $file ]] || continue
    configured=$(sed -n 's/^SSH_PORT=//p' "$file")
    [[ $configured == "$port" ]] && return 1
  done
  command -v ss >/dev/null 2>&1 && ss -H -ltn | awk -v p="$port" '{ x=$4; sub(/^.*:/,"",x); if (x==p) found=1 } END { exit found }'
}

next_port() {
  prepare_projects_dir
  exec 9>"$PROJECTS/.lock"
  flock -x 9 || die "flock is required"
  for port in $(seq 22000 22999); do port_free "$port" && { echo "$port"; flock -u 9; exec 9>&-; return; }; done
  flock -u 9; exec 9>&-; die "no SSH ports remain in 22000-22999"
}

herdr_create() {
  local project=$1 agent=${DEFAULT_AGENT:-none} result workspace pane tab tab_pane
  result=$(compose_hub exec -T herdr herdr workspace create --cwd /srv/devctl/herdr --label "$project" --no-focus)
  workspace=$(printf '%s\n' "$result" | compose_hub exec -T herdr jq -r '.result.workspace.workspace_id')
  pane=$(printf '%s\n' "$result" | compose_hub exec -T herdr jq -r '.result.root_pane.pane_id')
  [[ $workspace != null && $pane != null ]] || die "Herdr workspace creation failed"
  compose_hub exec -T herdr herdr pane run "$pane" "dev-enter $project shell" >/dev/null
  [[ $agent == none ]] && return
  tab=$(compose_hub exec -T herdr herdr tab create --workspace "$workspace" --cwd /srv/devctl/herdr --label "$agent" --no-focus)
  tab_pane=$(printf '%s\n' "$tab" | compose_hub exec -T herdr jq -r '.result.root_pane.pane_id')
  [[ $tab_pane != null ]] || die "Herdr tab creation failed"
  compose_hub exec -T herdr herdr pane run "$tab_pane" "HERDR_AGENT=$agent dev-enter $project $agent" >/dev/null
}

create_cmd() {
  ensure_bundle
  load_config
  local repo=$1 name='' branch='' depth='' preview=3000 port='' file project_dir
  shift
  while (($#)); do
    case $1 in
      --name) name=${2:-}; shift 2;;
      --branch) branch=${2:-}; shift 2;;
      --depth) depth=${2:-}; shift 2;;
      --preview-port) preview=${2:-}; shift 2;;
      --ssh-port) port=${2:-}; shift 2;;
      *) die "unknown create option: $1";;
    esac
  done
  valid_repo "$repo" || die "repository must be a credential-free HTTPS URL"
  valid_branch "$branch" || die "invalid branch"
  [[ -z $depth ]] || valid_num "$depth" 1 2147483647 || die "invalid clone depth"
  [[ -n $name ]] || name=${repo##*/}; name=${name%.git}; name=$(printf '%s' "$name" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9-]/-/g; s/--*/-/g; s/^-*//; s/-*$//; s/\(.........................................\).*/\1/')
  valid_name "$name" || die "could not derive a valid project name; use --name"
  [[ -z $port ]] && port=$(next_port)
  valid_num "$port" 22000 22999 || die "SSH port must be 22000-22999"
  valid_num "$preview" 1 65535 || die "preview port is invalid"
  file=$PROJECTS/$name.env; [[ ! -e $file ]] || die "project already exists: $name"
  project_dir=$STATE/projects/$name
  root install -d -m 0755 "$project_dir"
  root install -d -m 0700 "$project_dir/repo" "$project_dir/ssh-host-keys" "$project_dir/vscode-server"
  printf '%s\n' "PROJECT_NAME=$name" "PROJECT_DIR=$project_dir" "REPO_URL=$repo" "REPO_BRANCH=$branch" "REPO_DEPTH=$depth" \
    "SSH_PORT=$port" "PREVIEW_PORT=$preview" "BASE_DOMAIN=$BASE_DOMAIN" "TRAEFIK_NETWORK=$TRAEFIK_NETWORK" \
    "TRAEFIK_ENTRYPOINT=$TRAEFIK_ENTRYPOINT" "TRAEFIK_AUTH_MIDDLEWARE=$TRAEFIK_AUTH_MIDDLEWARE" \
    "TRAEFIK_CERT_RESOLVER=$TRAEFIK_CERT_RESOLVER" "WORKSPACE_IMAGE=ghcr.io/lucurlings/devctl-workspace:latest" \
    'WORKSPACE_CPUS=4' 'WORKSPACE_MEMORY=8G' > "$file"
  chmod 0600 "$file"
  docker compose --project-name "devctl-$name" --env-file "$file" -f "$HERE/workspace.compose.yml" up -d
  wait_healthy "devctl-$name" "$file" "$HERE/workspace.compose.yml" workspace
  herdr_create "$name"
  cat <<EOF
Created $name
Code: https://$name.code.$BASE_DOMAIN
Preview: https://$name.dev.$BASE_DOMAIN

Add this block to your laptop's ~/.ssh/config:
Host dev-$name
    HostName 127.0.0.1
    Port $port
    User developer
    ProxyJump <server-alias>
    IdentityFile ~/.ssh/id_ed25519
EOF
}

login_cmd() {
  case ${1:-} in
    github) compose_hub exec --user developer -e HOME=/home/developer herdr gh auth login --hostname github.com --git-protocol https --web;;
    codex) compose_hub exec --user developer -e HOME=/home/developer herdr codex login --device-auth;;
    claude) compose_hub exec --user developer -e HOME=/home/developer herdr claude auth login;;
    *) die "login requires github, codex, or claude";;
  esac
}

list_cmd() { for file in "$PROJECTS"/*.env; do [[ -e $file ]] || continue; sed -n 's/^PROJECT_NAME=//p' "$file"; done; }

telegram_cmd() {
  ensure_bundle
  local token='' users='' group=''
  while (($#)); do case $1 in --token-file) token=${2:-}; shift 2;; --allowed-users) users=${2:-}; shift 2;; --group-id) group=${2:-}; shift 2;; *) die "unknown telegram option: $1";; esac; done
  [[ $users =~ ^[0-9]+(,[0-9]+)*$ && $group =~ ^-100[0-9]+$ && -f $token ]] || die "invalid Telegram settings"
  [[ $(stat -c '%a' "$token") == 600 ]] || die "token file must have mode 0600"
  sed -i.bak -e "s/^TELEGRAM_ALLOWED_USERS=.*/TELEGRAM_ALLOWED_USERS=$users/" -e "s/^TELEGRAM_GROUP_ID=.*/TELEGRAM_GROUP_ID=$group/" "$HERE/hub.env"; rm -f "$HERE/hub.env.bak"
  root install -m 0600 "$token" "$STATE/secrets/telegram-bot-token"
  compose_hub --profile telegram up -d
}

main() {
  case ${1:-} in
    install) shift; install_cmd "$@";;
    create) (($# >= 2)) || die "create requires a repository URL"; shift; create_cmd "$@";;
    list) list_cmd;;
    telegram) shift; telegram_cmd "$@";;
    login) shift; login_cmd "$@";;
    -h|--help|help) usage;;
    *) usage; exit 2;;
  esac
}
main "$@"
