services:
  adguard:
    container_name: adguard
    image: adguard/adguardhome:v0.107.63
    restart: unless-stopped
    ports:
      - "3000:3000/tcp"  # Web UI
      - "53:53/tcp"      # DNS TCP
      - "53:53/udp"      # DNS UDP
      # - "67:67/udp"      # DHCP UDP
      # - "68:68/udp"      # DHCP UDP
    volumes:
      - $DOCKERDIR/appdata/adguard/work:/opt/adguardhome/work
      - $DOCKERDIR/appdata/adguard/conf:/opt/adguardhome/conf
    environment:
      - TZ=$TZ # Set your timezone
