services:
#    https://docs.anythingllm.com/installation-docker/local-docker
    anythingllm:
        container_name: anythingllm
        image: mintplexlabs/anythingllm:1.8.3
        restart: unless-stopped
        networks:
            - t3_proxy
        cap_add:
            - SYS_ADMIN
        volumes:
            - $DATADIR/anythingllm:/app/server/storage
            - $DOCKERDIR/appdata/anythingllm/.env:/app/server/.env
        labels:
          - "traefik.enable=true"
          # HTTP Routers
          - "traefik.http.routers.anythingllm.entrypoints=websecure"
          - "traefik.http.routers.anythingllm.rule=Host(`llm.$DOMAINNAME`)"
          # Middlewares
          - "traefik.http.routers.anythingllm.middlewares=chain-oauth@file"
          # - "traefik.http.routers.jellyfin.middlewares=middlewares-basic-auth@file" # For Basic HTTP Authentication
          # Http Services
          - "traefik.http.routers.anythingllm.service=anythingllm-svc"
          - "traefik.http.services.anythingllm-svc.loadbalancer.server.port=3001"