services:
  calibre:
    image: lscr.io/linuxserver/calibre:8.5.0
    container_name: calibre
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      # - PASSWORD= #optional
      # - CLI_ARGS= #optional
    volumes:
      - $DOCKERDIR/appdata/calibre:/config
      - $DATADIR/media/books:/books
    # ports:
    #   - 8080:8080
    #   - 8181:8181
    #   - 8081:8081
    restart: unless-stopped
    networks:
      - t3_proxy
    labels:
      - "traefik.enable=true"
      # HTTP Routers Auth
      - "traefik.http.routers.calibre-rtr.entrypoints=websecure"
      - "traefik.http.routers.calibre-rtr.rule=Host(`calibre.$DOMAINNAME`) || Host(`c.$DOMAINNAME`)"
      - "traefik.http.routers.calibre-rtr.priority=99"
      # Middlewares
      - "traefik.http.routers.calibre-rtr.middlewares=chain-oauth@file"
      # HTTP Services
      - "traefik.http.routers.calibre-rtr.service=calibre-svc"
      - "traefik.http.services.calibre-svc.loadbalancer.server.port=8080"