services:
    cyberchef:
      container_name: cyberchef
      image: ghcr.io/k8s-at-our-homes/cyberchef:10.19.4
      security_opt:
        - no-new-privileges:true
      restart: unless-stopped
      # profiles: ["apps", "all"]
      networks:
        - t3_proxy
      labels:
        - "traefik.enable=true"
        # HTTP Routers
        - "traefik.http.routers.cyberchef-rtr.entrypoints=websecure"
        - "traefik.http.routers.cyberchef-rtr.rule=Host(`cyberchef.$DOMAINNAME`)"
        # Middlewares
        - "traefik.http.routers.cyberchef-rtr.middlewares=chain-oauth@file"
        # HTTP Services
        - "traefik.http.routers.cyberchef-rtr.service=cyberchef-svc"
        - "traefik.http.services.cyberchef-svc.loadbalancer.server.port=8080"