services:
  ddclient:
    image: lscr.io/linuxserver/ddclient:4.0.0
    container_name: ddclient
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
    volumes:
      - $DOCKERDIR/appdata/ddclient:/config
    restart: unless-stopped