services:
  deluge:
    image: lscr.io/linuxserver/deluge:2.2.0
    container_name: deluge
    network_mode: service:gluetun
    # network_mode: service:vpn
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
      - DELUGE_LOGLEVEL=info #optional
    volumes:
      - $DOCKERDIR/appdata/deluge:/config
      - $DATADIR/torrents:/downloads
    restart: unless-stopped