services:
  deluge:
    image: lscr.io/linuxserver/deluge:2.2.0
    container_name: deluge
    network_mode: service:gluetun
    # network_mode: service:vpn
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
      - DELUGE_LOGLEVEL=info #optional
    volumes:
      - $DOCKERDIR/appdata/deluge:/config
      - $DATADIR/torrents:/downloads
    # ports:
    #   - 8112:8112
    #   - 6881:6881
    #   - 6881:6881/udp
    #   - 58846:58846 #optional
    restart: unless-stopped


# services:
#   deluge:
#     container_name: deluge
#     image: linuxserver/deluge:latest
#     # profiles:
#     #   - all
#     #   - media
#     restart: unless-stopped
#     # networks:
#     #   - t3_proxy
#     #   - socket_proxy
#     network_mode: service:vpn # run on the vpn network
#     environment:
#       - PUID=${PUID} # default user id, defined in .env
#       - PGID=${PGID} # default group id, defined in .env
#       - TZ=${TZ} # timezone, defined in .env
#     volumes:
#       - $DOCKERDIR/appdata/deluge:/config
#       - $DATADIR/torrents:/downloads