services:
  nextcloud:
    container_name: nextcloud
    image: nextcloud:30.0.3
    env_file: ${DOCKERDIR}/appdata/nextcloud/nextcloud.env
    networks:
      - t3_proxy
      - nextcloud_internal
    labels:
      - "traefik.enable=true"
      # HTTP Routers
      - "traefik.http.routers.nextcloud.entrypoints=websecure"
      - "traefik.http.routers.nextcloud.rule=Host(`nextcloud.$DOMAINNAME`)"
      # Middlewares
      # - "traefik.http.routers.jellyfin.middlewares=middlewares-basic-auth@file" # For Basic HTTP Authentication
      # Http Services
      - "traefik.http.routers.nextcloud.service=nextcloud-svc"
      - "traefik.http.services.nextcloud-svc.loadbalancer.server.port=80"

    volumes:
      - ${DOCKERDIR}/appdata/nextcloud/html:/var/www/html
      - ${DOCKERDIR}/appdata/nextcloud/apps:/var/www/html/custom_apps
      - ${DOCKERDIR}/appdata/nextcloud/config:/var/www/html/config
      - ${DATADIR}/nextcloud:/var/www/html/data

  nextcloud-maria-db:
    container_name: nextcloud-db
    image: mariadb:11.6 
    env_file: ${DOCKERDIR}/appdata/nextcloud/nextcloud.env
    networks:
      - nextcloud_internal
    volumes:
      - ${INTERNALDIR}/nextcloud/db:/var/lib/mysql

  nextcloud-maria-db-backup:
    container_name: nextcloud-db-backup
    image: mariadb:11.6
    env_file: ${DOCKERDIR}/appdata/nextcloud/nextcloud-db-backup.env
    volumes:
      - ${INTERNALDIR}/nextcloud/database-dump:/dump
      - /etc/localtime:/etc/localtime:ro
    entrypoint: |
      bash -c 'bash -s <<EOF
      trap "break;exit" SIGHUP SIGINT SIGTERM
      sleep 2m
      while /bin/true; do
        mysqldump -h db --all-databases | gzip -c > /dump/dump_\`date +%d-%m-%Y"_"%H_%M_%S\`.sql.gz
        ls -tr /dump/dump_*.sql.gz | head -n -"$$BACKUP_NUM_KEEP" | xargs -r rm
        sleep $$BACKUP_FREQUENCY
      done
      EOF'
    networks:
      - nextcloud_internal

  nextcloud-redis:
    container_name: nextcloud-redis
    image: redis:alpine
    networks:
      - nextcloud_internal
    volumes:
      - ${INTERNALDIR}/nextcloud/redis:/data

  nextcloud-cron:
    container_name: nextcloud-cron
    image: nextcloud:30.0.3
    volumes:
      - ${DOCKERDIR}/appdata/nextcloud/html:/var/www/html
      - ${DOCKERDIR}/appdata/nextcloud/apps:/var/www/html/custom_apps
      - ${DOCKERDIR}/appdata/nextcloud/config:/var/www/html/config
      - ${DATADIR}/nextcloud:/var/www/html/data
    user: www-data
    networks:
      - nextcloud_internal
    entrypoint: |
      bash -c 'bash -s <<EOF
        trap "break;exit" SIGHUP SIGINT SIGTERM
        while [ ! -f /var/www/html/config/config.php ]; do
          sleep 1
        done
        while true; do
          php -f /var/www/html/cron.php
          sleep 15m
        done
      EOF'

networks:
  nextcloud_internal:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.12.0/24