services:
  actual-server:
    image: docker.io/actualbudget/actual-server:latest
    container_name: actual-server
    # environment:
      # Uncomment any of the lines below to set configuration options.
      # - ACTUAL_HTTPS_KEY=/data/selfhost.key
      # - ACTUAL_HTTPS_CERT=/data/selfhost.crt
      # - ACTUAL_PORT=5006
      # - ACTUAL_UPLOAD_FILE_SYNC_SIZE_LIMIT_MB=20
      # - ACTUAL_UPLOAD_SYNC_ENCRYPTED_FILE_SYNC_SIZE_LIMIT_MB=50
      # - ACTUAL_UPLOAD_FILE_SIZE_LIMIT_MB=20
      # See all options and more details at https://actualbudget.github.io/docs/Installing/Configuration
      # !! If you are not using any of these options, remove the 'environment:' tag entirely.
    volumes:
      # Change './actual-data' below to the path to the folder you want Actual to store its data in on your server.
      # '/data' is the path Actual will look for its files in by default, so leave that as-is.
      - $DOCKERDIR/appdata/actual-server:/data
    restart: unless-stopped
    networks:
      - t3_proxy
      - socket_proxy
    labels:
      - "traefik.enable=true"
      # HTTP Routers Auth
      - "traefik.http.routers.actual-server-rtr.entrypoints=websecure"
      - "traefik.http.routers.actual-server-rtr.rule=Host(`actual-server.$DOMAINNAME`) || Host(`as.$DOMAINNAME`)"
      - "traefik.http.routers.actual-server-rtr.priority=99"
      # Middlewares
      - "traefik.http.routers.actual-server-rtr.middlewares=chain-oauth@file"
      # HTTP Services
      - "traefik.http.routers.actual-server-rtr.service=actual-server-svc"
      - "traefik.http.services.actual-server-svc.loadbalancer.server.port=5006"