services:
  gatus:
    container_name: gatus
    image: twinproduction/gatus:v5.11.0
    restart: unless-stopped
    networks:
      - t3_proxy
      - socket_proxy
    volumes:
      - $DOCKERDIR/appdata/gatus:/config
    labels:
      - "traefik.enable=true"
      # HTTP Routers
      - "traefik.http.routers.gatus-rtr.entrypoints=websecure"
      - "traefik.http.routers.gatus-rtr.rule=Host(`gatus.$DOMAINNAME_HS`) || Host(`status.$DOMAINNAME_HS`)"
      # Middlewares
      - "traefik.http.routers.gatus-rtr.middlewares=chain-no-auth@file"
      # HTTP Services
      - "traefik.http.routers.gatus-rtr.service=gatus-svc"
      - "traefik.http.services.gatus-svc.loadbalancer.server.port=8080"