services:
    anythingllm:
        container_name: anythingllm
        image: mintplexlabs/anythingllm:1.4.0
        networks:
          - t3_proxy
        cap_add:
            - SYS_ADMIN
        volumes:
            - $DATADIR/anythingllm:/app/server/storage
            - $DOCKERDIR/appdata/anythingllm/.env:/app/server/.env
        environment:
            - STORAGE_DIR=/app/server/storage
        labels:
          - "traefik.enable=true"
          # HTTP Routers
          - "traefik.http.routers.anythingllm.entrypoints=websecure"
          - "traefik.http.routers.anythingllm.rule=Host(`llm.$DOMAINNAME`)"
          # Middlewares
          # - "traefik.http.routers.jellyfin.middlewares=middlewares-basic-auth@file" # For Basic HTTP Authentication
          # Http Services
          - "traefik.http.routers.anythingllm.service=anythingllm-svc"
          - "traefik.http.services.anythingllm-svc.loadbalancer.server.port=3001"