services:
  # Gluetun - VPN Client for Docker Containers and More
  # Gluetun only for use by torrent clients + on demand lan devices.
  # Arr apps do not need VPN (not recommended), unless you have ISP/country restrictions.
  gluetun:
    image: qmcgaw/gluetun:v3.39.1
    container_name: gluetun
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    # profiles: ["core", "all"]
    networks:
      - t3_proxy
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    ports:
      - 6881:6881
      - 6881:6881/udp
      # - "8112:8112" # Exposing qBittorrent through Docker Host LAN IP
    # #   - 8888:8888/tcp # HTTP proxy
    # #   - 8388:8388/tcp # Shadowsocks
    # #   - 8388:8388/udp # Shadowsocks
    volumes:
      - $DOCKERDIR/appdata/gluetun:/gluetun
      - $DOCKERDIR/appdata/gluetun-wg/wg0.conf:/gluetun/wireguard/wg0.conf
    environment:
      - TZ=${TZ}
      # Wireguard
      - VPN_SERVICE_PROVIDER=custom
      - VPN_TYPE=wireguard
      # - WIREGUARD_PRIVATE_KEY=${GLUETUN_WIREGUARD_PRIVATE_KEY}
      # - WIREGUARD_ADDRESSES=${GLUETUN_WIREGUARD_ADDRESSES}
      # - SERVER_COUNTRIES=Netherlands
      # # OpenVPN
      # VPN_SERVICE_PROVIDER: nordvpn
      # VPN_TYPE: openvpn
      # OPENVPN_USER: $NORDVPN_USERNAME
      # OPENVPN_PASSWORD: $NORDVPN_PASSWORD
      - DNS=192.168.1.198:53
    labels:
      - "traefik.enable=true"
      # HTTP Routers
      - "traefik.http.routers.gluetun-deluge-rtr.entrypoints=websecure"
      - "traefik.http.routers.gluetun-deluge-rtr.rule=Host(`deluge.$DOMAINNAME`)"
      # Middlewares
      - "traefik.http.routers.gluetun-deluge-rtr.middlewares=chain-oauth@file"
      # HTTP Services
      - "traefik.http.routers.gluetun-deluge-rtr.service=gluetun-svc"
      - "traefik.http.services.gluetun-svc.loadbalancer.server.port=8112"