services:
    flaresolverr:
        image: ghcr.io/flaresolverr/flaresolverr:latest
        container_name: flaresolverr
        restart: unless-stopped
        environment:
            - LOG_LEVEL=info
        ports:
            - '8191:8191'
        networks:
            - t3_proxy
            - socket_proxy
