services:
  jellyseerr:
    image: fallenbagel/jellyseerr:2.5.2
    container_name: jellyseerr
    restart: unless-stopped
    networks:
      - t3_proxy
      - socket_proxy
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - $DOCKERDIR/appdata/jellyseerr:/app/config
    labels:
      - "traefik.enable=true"
      # HTTP Routers
      - "traefik.http.routers.jellyseerr.entrypoints=websecure"
      - "traefik.http.routers.jellyseerr.rule=Host(`jellyseerr.$DOMAINNAME`)"
      # Middlewares
      # - "traefik.http.routers.jellyseerr.middlewares=middlewares-basic-auth@file" # For Basic HTTP Authentication
      # Http Services
      - "traefik.http.routers.jellyseerr.service=jellyseerr-svc"
      - "traefik.http.services.jellyseerr-svc.loadbalancer.server.port=5055"