services:
  lucurlings-website:
    image: ghcr.io/lucurlings/lucurlings.nl:latest
    pull_policy: always
    container_name: lucurlings.nl
    restart: unless-stopped
    networks:
      - t3_proxy
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://127.0.0.1/ || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    labels:
      - "traefik.enable=true"
      # HTTP Routers
      - "traefik.http.routers.lucurlings.entrypoints=websecure"
      - "traefik.http.routers.lucurlings.rule=Host(`$DOMAINNAME`)"
      # Middlewares
#      - "traefik.http.routers.lucurlings.middlewares=chain-oauth@file"
      # Http Services
      - "traefik.http.routers.lucurlings.service=lucurlings-svc"
      - "traefik.http.services.lucurlings-svc.loadbalancer.server.port=80"