services:
  recommendarr:
    # IF NOT using a reverse proxy uncomment the image tag to use prebuilt
    image: tannermiddleton/recommendarr:latest
    networks:
      - t3_proxy
    # For reverse proxy setup uncomment and setup the URLs:
    # build:
    #   context: .
    #   args:
    #    # Build time arguments - set these for the Vue.js build process
    #    # Only needed for reverse proxy setup:
    #    # - BASE_URL=${BASE_URL:-/}
    container_name: recommendarr
    ports:
      - 14131:14131  # Unified port for both frontend and API
    # This is needed to allow the container to access services on the host machine
    # For example, when connecting to Sonarr, Radarr, Plex etc. running on the host (I think?)
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"
    environment:
      - NODE_ENV=production
      - DOCKER_ENV=false
      - PORT=14131
      # Runtime environment variables
      # For reverse proxy setups, uncomment and modify these do NOT forget the build section above
      #- PUBLIC_URL=https://recommendarr.yourdomain.com
      - PUBLIC_URL=${PUBLIC_URL:-http://localhost:${PORT:-3000}}
      # Uncomment to force secure cookies even over HTTP (only use if behind HTTPS reverse proxy)
      #- FORCE_SECURE_COOKIES=true
    volumes:
      - $DOCKERDIR/appdata/recommendarr:/app/server/data
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      # HTTP Routers Auth
      - "traefik.http.routers.recommendarr-rtr.entrypoints=websecure"
      - "traefik.http.routers.recommendarr-rtr.rule=Host(`recommendarr.$DOMAINNAME`)"
      - "traefik.http.routers.recommendarr-rtr.priority=99"
      # Middlewares
      - "traefik.http.routers.recommendarr-rtr.middlewares=chain-oauth@file"
      # HTTP Services
      - "traefik.http.routers.recommendarr-rtr.service=recommendarr-svc"
      - "traefik.http.services.recommendarr-svc.loadbalancer.server.port=14131"