services:
    timemachine:
      image: mbentley/timemachine:latest
      restart: unless-stopped
      container_name: timemachine
      network_mode: host
      environment:
        - TM_USERNAME=$TM_USERNAME
        - TM_GROUPNAME=$TM_GROUPNAME
        - PASSWORD=$TM_PASSWORD
        - TM_UID=$PUID
        - TM_GID=$PGID
        - SET_PERMISSIONS=false
        - VOLUME_SIZE_LIMIT=1000000000000
      volumes:
        - $DATADIR/timemachine:/opt/$TM_USERNAME
      tmpfs: /run/samba